### ISSUE TITLE
NER Inference Example

### ISSUE THREAD

**Issue by Perevalov** [M3RG-IITD/MatSciBERT#6] opened 2023-05-02 15:49 UTC
Dear authors, I was trying to run the NER inference with the model and came up with the following code:

```python
import torch

from transformers import (
    AutoConfig,
    AutoModelForTokenClassification,
    AutoTokenizer,
)

if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

tokenizer_kwargs = {
    'cache_dir': "./cache",
    'use_fast': True,
    'revision': 'main',
    'use_auth_token': None,
    'model_max_length': 512
}
tokenizer = AutoTokenizer.from_pretrained('m3rg-iitd/matscibert', **tokenizer_kwargs)

config_kwargs = {
    'num_labels': 15,
    'cache_dir': "./cache",
    'revision': 'main',
    'use_auth_token': None,
}
config = AutoConfig.from_pretrained('m3rg-iitd/matscibert', **config_kwargs)

model = AutoModelForTokenClassification.from_pretrained('m3rg-iitd/matscibert', config=config)

text = "AgCuO phase diagram"
encoded_input = tokenizer(text, return_tensors="pt")

output = model(**encoded_input)
scores = output.logits
predictions = torch.argmax(scores, dim=2)

tags = []
for i, token in enumerate(tokenizer.tokenize(text)):
  tag_id = predictions[0][i].item()
  tag = model.config.id2label[tag_id]
  tags.append(tag)
print(tags)
```

I get the following output: `['LABEL_9', 'LABEL_9', 'LABEL_9', 'LABEL_3', 'LABEL_13']`

How do I get the meaningful tag names and does this example make sence at all?

**Comment by zakidotai** [comment] 2023-05-03 10:55
Did you try running this [example code](https://github.com/M3RG-IITD/MatSciBERT/blob/main/ner/ner_inference.ipynb) that we have shared in the repository? Let me know if this helps.

**Comment by zakidotai** [comment] 2023-05-13 05:27
@Perevalov You can reopen the issue in case you have follow up questions.

**Comment by jiveshwari** [comment] 2023-10-26 10:11
Dear Authors,

While running the example ner_inference notebook provided in the MatSciBERT repository. I encountered the following error when I ran, 

`python
model = BERT_CRF('m3rg-iitd/matscibert', device, config, cache_dir)
`

The warning and error:

```python 
Some weights of BertForTokenClassification were not initialized from the model checkpoint at m3rg-iitd/matscibert and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{
	"name": "TypeError",
	"message": "__init__() got an unexpected keyword argument 'num_tags'",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/jiveshwarichinchghare/Documents/LASS_KG/NER_18thOCT/MatSciBERT/ner/ner_inference.ipynb Cell 19 line 1
----> <a href='vscode-notebook-cell:/Users/jiveshwarichinchghare/Documents/LASS_KG/NER_18thOCT/MatSciBERT/ner/ner_inference.ipynb#X24sZmlsZQ%3D%3D?line=0'>1</a> model = BERT_CRF('m3rg-iitd/matscibert', device, config, cache_dir)
      <a href='vscode-notebook-cell:/Users/jiveshwarichinchghare/Documents/LASS_KG/NER_18thOCT/MatSciBERT/ner/ner_inference.ipynb#X24sZmlsZQ%3D%3D?line=1'>2</a> #model = AutoModelForTokenClassification.from_pretrained('m3rg-iitd/matscibert', config=config)

File ~/Documents/LASS_KG/NER_18thOCT/MatSciBERT/ner/models.py:66, in BERT_CRF.__init__(self, model_name, device, config, cache_dir)
     62 self.device = device
     63 self.encoder = AutoModelForTokenClassification.from_pretrained(model_name, from_tf=False, config=config, 
     64                                                                cache_dir=cache_dir, revision=model_revision,
     65                                                                use_auth_token=None)
---> 66 self.crf = BIO_Tag_CRF(config.num_labels, device, batch_first=True)

File ~/Documents/LASS_KG/NER_18thOCT/MatSciBERT/ner/models.py:15, in BIO_Tag_CRF.__init__(self, num_tags, device, batch_first)
     14 def __init__(self, num_tags: int, device, batch_first: bool = False):
---> 15     super(BIO_Tag_CRF, self).__init__(num_tags=num_tags, batch_first=batch_first)
     16     self.device = device
     17     start_transitions = self.start_transitions.clone().detach()

TypeError: __init__() got an unexpected keyword argument 'num_tags'"
}
```

This error appears to stem from the constructor of the BIO_Tag_CRF class in the models.py file. Specifically, the issue seems to be related to the presence of an unexpected keyword argument, 'num_tags,' in the constructor call. The traceback suggests that this error is preventing the successful initialization of the Conditional Random Field (CRF) component used in the NER model. I have been unable to pinpoint the root cause and solution of this issue. Therefore, I am reaching out to request your expert guidance and support in resolving this matter. 

I eagerly anticipate your response and assistance. 
Thank you for your time and consideration.

**Comment by zakidotai** [comment] 2023-10-26 10:47
@jiveshwari 

Can you please confirm if the versions of libraries are same as recommended in the repository? Can you also confirm if you made any changes in the code provided [here](https://github.com/M3RG-IITD/MatSciBERT/blob/main/ner/ner_inference.ipynb)

**Comment by zakidotai** [comment] 2023-11-02 03:46
@jiveshwari I hope your issue is resolved. If not, you can reopen this issue.

**Closed as completed** 2023-11-02 03:46 UTC
